retry_count = 5
text_file_extensions = [
    ".c",
    ".cpp",
    ".go",
    ".h",
    ".java",
    ".mod",
    ".md",
    ".py",
    ".rs",
    ".sh",
    ".txt",
]
[[ignores]]
url = "https://csrc.nist.gov/pubs/fips/186-4/final"
codes = [200, 404]
reason = """
This URL seems to sometimes return 404 to requests from GitHub Actions' runners,
and the issue cannot be handled with retries."""
considered_alternatives = [
    "https://www.omgwiki.org/dido/doku.php?id=dido:public:ra:xapend:xapend.b_stds:tech:nist:dss", # as flaky as the original
]

[[ignores]]
url = "https://mathoverflow.net/questions/207922/quickest-and-or-most-elementary-proof-of-principal-iff-splits-completely"
codes = [200, 403]
reason = """
This URL seems to sometimes return 403 to requests from GitHub Actions' runners,
and the issue cannot be handled with retries."""
considered_alternatives = [
    "https://core.ac.uk/download/pdf/82407901.pdf", # TODO: check the existence of (principal => splitting)
]

[[ignores]]
url = "https://www.universiteitleiden.nl/binaries/content/assets/science/mi/scripties/dobbendebruynbach.pdf"
codes = [404]
reason = """
This page has gone 404. (2025-02-27)
"""
considered_alternatives = [
    "https://web.archive.org/web/20240525113801/https:%2F%2Fwww.universiteitleiden.nl/binaries/content/assets/science/mi/scripties/dobbendebruynbach.pdf", # If 404 persists, switch to this page.
]

[[ignores]]
url = "https://dl.acm.org/doi/pdf/10.1145/2508859.2516734"
codes = [403]
reason = """
This page sometimes returns 403.
"""
considered_alternatives = [
    "",
]

[[ignores]]
url = "https://mathoverflow.net/questions/71704/computing-the-q-series-of-the-j-invariant"
codes = [403]
reason = """
This page sometimes returns 403.
"""
considered_alternatives = [
    "",
]

[[ignores]]
url = "https://math.stackexchange.com/questions/3951434/generators-of-level-2-modular-forms"
codes = [403]
reason = """
This page sometimes returns 403.
"""
considered_alternatives = [
    "",
]

[[ignores]]
url = "https://mathoverflow.net/questions/71704/computing-the-q-series-of-the-j-invariant"
codes = [403]
reason = """
This page sometimes returns 403.
"""
considered_alternatives = [
    "",
]

[[ignores]]
url = "https://math.stackexchange.com/questions/2000978/proof-of-the-disjunction-property"
codes = [403]
reason = """
This page sometimes returns 403.
"""
considered_alternatives = [
    "",
]
