name: Link checker

on:
  schedule:
    - cron: '10 12 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check hyperlinks
        run: |
          go install github.com/koba-e964/link-checker@latest
          link-checker
